#!/bin/bash

AUR="https://aur.archlinux.org"

package="$1"

if [[ "$package" == "--help" || "$package" == "-h" ]]; then
    cat <<EOF
Usage: $(basename $0) [package]

  If you do not supply a package name, maur will list all available AUR packages.

  If you do supply a package name, maur will clone it into a temporary directory,
  open the PKGBUILD for you to review, and then prompt you to confirm installation.
EOF
    exit
fi

if [ -z "$package" ]; then
    curl -s "${AUR}/packages.gz" | zcat
    exit
fi

# Confirm package exists
status=$(curl -s -I "${AUR}/packages/${package}" | head -n 1 | awk '{print $2}')
if [[ "$status" != "200" ]]; then
    echo "No such package: ${package}"
    exit 1
fi

dir=$(mktemp -d)

function cleanup() {
    echo
    echo "Cleaning up..."
    rm -rf $dir
}

set -e
trap cleanup ERR
trap cleanup EXIT

# Clone
cd $dir
echo "Cloning ${package}..."
git clone "${AUR}/${package}.git" ./ >/dev/null 2>&1

# Edit
$EDITOR ./PKGBUILD

# Confirm
echo
echo "If you want to make any changes before install, the package is in ${dir}"
echo
read -p "Type yes to confirm installation of ${package}: " confirm
if [[ "$confirm" != "yes" ]]; then
    exit 1
fi

# Install
echo
echo "Installing ${package}..."
makepkg -si
